In [ ]:
#1. What is a Python library? Why do we use Python libraries?

->
A Python library is a collection of modules or functions that extend the capabilities of the Python programming language. These libraries provide reusable code and pre-written functions that can be easily imported into Python scripts or programs, saving developers time and effort in implementing common tasks or functionalities.
There are several reasons why we use Python libraries:
1)Reusability: Python libraries contain pre-written code that can be reused in different projects or applications, reducing the need to write code from scratch.
2)Efficiency: Libraries often provide optimized implementations of algorithms or functionalities, resulting in faster execution times compared to writing custom code.
3)Community-driven: Python has a large and active community of developers who contribute to the development of various libraries. These libraries are often well-maintained, documented, and tested by the community.
4)Domain-specific functionality: Many Python libraries are specialized for specific domains such as data science, web development, machine learning, scientific computing, etc. These libraries provide tools and functionalities tailored to the needs of those domains.
5)Interoperability: Python libraries can often interact with other programming languages and platforms, allowing developers to integrate Python code into existing systems or workflows.

In [ ]:
#2. What is the difference between Numpy array and List?
1)Data Types: NumPy arrays can only contain elements of the same data type, whereas Python lists can hold elements of different data types.
2)Performance: NumPy arrays are more efficient in terms of memory usage and computational speed compared to Python lists, especially for large datasets. This is because NumPy arrays are implemented in C and optimized for numerical operations.
3)Functionality: NumPy arrays provide a wide range of mathematical functions and operations for array manipulation, such as element-wise addition, multiplication, trigonometric functions, linear algebra operations, etc. Python lists do not offer these functionalities natively.
4)Size: NumPy arrays have a fixed size, meaning the size of a NumPy array cannot be changed once it is created. In contrast, Python lists are dynamic and can grow or shrink in size as elements are added or removed.
5)Indexing and Slicing: Indexing and slicing operations are more convenient and efficient with NumPy arrays compared to Python lists. NumPy arrays support multidimensional indexing and slicing, whereas Python lists only support one-dimensional indexing and slicing.
6)Memory Usage: NumPy arrays typically consume less memory compared to Python lists, especially for large datasets, because NumPy arrays store data more efficiently and have a fixed data type.

In [10]:
#3. Find the shape, size and dimension of the following array?
#[[1, 2, 3, 4]
#5, 6, 7, 8],
#[9, 10, 11, 12]]
import numpy as np

arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
arr


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:

arr.shape

(3, 4)

In [12]:
arr.size

12

In [13]:
arr.ndim

2

In [14]:
"""4. Write python co^e to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]"""
first_row=arr[0]
first_row

array([1, 2, 3, 4])

In [15]:
"""5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]"""


element = arr[2, 3]
print("Element at third row and fourth column:", element)

Element at third row and fourth column: 12


In [16]:
"""6. Write code to extract all odd index elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]"""
odd_index_elements = arr[:, 1::2]  # Slice the array to get elements at odd indices
print("Elements at odd indices:\n", odd_index_elements)

Elements at odd indices:
 [[ 2  4]
 [ 6  8]
 [10 12]]


In [17]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?
random_matrix = np.random.rand(3, 3)

print("Random 3x3 matrix:\n", random_matrix)

Random 3x3 matrix:
 [[0.07718421 0.13381334 0.31427085]
 [0.14422464 0.07217347 0.15492382]
 [0.54014117 0.55868367 0.77738215]]


In [18]:
#8. Describe the difference between np.random.rand and np.random.randn?
"""The main difference between np.random.rand and np.random.randn lies in the distribution of the generated random numbers:
1)np.random.rand: This function generates random numbers from a uniform distribution over the interval [0, 1). It takes the shape of the output array as input arguments and returns random numbers of that shape.
2)np.random.randn: This function generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1). It takes the shape of the output array as input arguments and returns random numbers of that shape.
In summary:
np.random.rand generates random numbers from a uniform distribution.
np.random.randn generates random numbers from a standard normal distribution.
"""
import numpy as np

# Generate random numbers from a uniform distribution
uniform_random_numbers = np.random.rand(2, 2)
print("Random numbers from a uniform distribution:\n", uniform_random_numbers)

# Generate random numbers from a standard normal distribution
normal_random_numbers = np.random.randn(2, 2)
print("Random numbers from a standard normal distribution:\n", normal_random_numbers)


Random numbers from a uniform distribution:
 [[0.40346787 0.03805224]
 [0.40679547 0.88763295]]
Random numbers from a standard normal distribution:
 [[-0.55877316 -1.54259874]
 [-1.08389848  0.12567556]]


In [19]:
"""9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]"""

new_arr = np.expand_dims(arr, axis=1)
print(new_arr)

[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]


In [20]:
"""10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]"""

transposed_arr = arr.T
print(transposed_arr)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [25]:
"""11. Consider the following matrix:
Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python:
1.index wise multiplication
2.Matix multiplication
3.Add both the matics
4.Subtact matix B from A
5.divide Matix B by A """


A=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
B=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [26]:
#1
index_wise_multiplication = A * B
print("Index-wise multiplication:")
print(index_wise_multiplication)

Index-wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [27]:
#2
matrix_multiplication = np.dot(A, B.T)  # Transpose B to match dimensions
print("Matrix multiplication:")
print(matrix_multiplication)

Matrix multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


In [28]:
#3
matrix_addition = A + B
print("Matrix addition:")
print(matrix_addition)

Matrix addition:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [29]:
#4
matrix_subtraction = A - B
print("Matrix subtraction:")
print(matrix_subtraction)

Matrix subtraction:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [30]:
#5
matrix_division = np.divide(B, A)
print("Matrix division:")
print(matrix_division)

Matrix division:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
#Which function in Numpy can be used to swap the byte order of an array?
"""
NumPy, you can use the byteswap() function to swap the byte order of an array. This function swaps the byte order of the elements in the array. You can specify the byte order using the byteorder parameter."""
import numpy as np

# Create an array with dtype int16
arr = np.array([1, 2, 3, 4], dtype=np.int16)
print("Original array:")
print(arr)

# Swap byte order
swapped_arr = arr.byteswap()
print("\nArray with byte order swapped:")
print(swapped_arr)


Original array:
[1 2 3 4]

Array with byte order swapped:
[ 256  512  768 1024]


In [ ]:
#13. What is the significance of the np.linalg.inv function?
"""
The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix. The significance of this function lies in its usefulness in solving systems of linear equations, particularly when dealing with matrices.
Here are some key points regarding the significance of np.linalg.inv:
1)Matrix Inversion: The function calculates the inverse of a given square matrix. This is important because it allows us to find the solution to linear systems of equations in matrix form, which may not be easy or possible using other methods.
2)Solving Linear Systems: In many scientific and engineering applications, linear systems of equations arise frequently. By computing the inverse of a matrix, we can solve these systems efficiently using matrix multiplication.
3)Numerical Stability: The np.linalg.inv function is implemented with numerical stability in mind. It employs efficient algorithms to handle large matrices and maintains accuracy even for matrices with ill-conditioned or nearly singular properties.
4)Applications in Statistics and Machine Learning: Matrix inversion is fundamental in various statistical and machine learning algorithms, such as linear regression, least squares estimation, and principal component analysis (PCA).
"""



In [ ]:
#14. What does the np.reshape function do, and how is it used?
"""The np.reshape function in NumPy is used to change the shape (dimensions) of an array without changing its data. It allows you to rearrange the elements of an array into a new shape while maintaining the same data.
Here's how np.reshape works and how it's used:
Changing Array Shape: The primary purpose of np.reshape is to change the shape of an array. You can specify the new shape as a tuple of integers representing the desired dimensions.
1)Original Data: The data in the array remains unchanged after reshaping. The reshaping operation simply rearranges how the data is interpreted without modifying the underlying elements.
2)Contiguous Data: Reshaping preserves the order of elements in the original array. For example, if the original array is stored in row-major order, the reshaped array will also maintain this order.
3)Compatible Shape: The new shape specified must be compatible with the number of elements in the original array. In other words, the total number of elements in the original array must equal the total number of elements in the reshaped array.
4)Usage: The np.reshape function is typically called as a method of a NumPy array """


In [34]:
#15. What is broadcasting in Numpy?
"""     
Broadcasting in NumPy is a powerful mechanism that allows arrays of different shapes to be combined or operated on together seamlessly. When performing element-wise operations between arrays, NumPy automatically broadcasts the arrays to make their shapes compatible if they don't have the same shape initially.
Here's how broadcasting works in NumPy:
1)Shape Compatibility: Broadcasting occurs when the dimensions of two arrays are compatible for element-wise operations. Two dimensions are compatible when either they are equal or one of them is 1.
2)Automatic Expansion: NumPy automatically expands the smaller array along the missing dimensions to match the shape of the larger array. This expansion happens conceptually without actually creating multiple copies of the data in memory.
3)Element-Wise Operations: After broadcasting, the element-wise operation is performed between the corresponding elements of the expanded arrays.
4)Efficient Computation: Broadcasting allows for efficient computation by avoiding the need to create multiple copies of the array data. Instead, NumPy intelligently operates on the arrays without unnecessary memory overhead.
5)Examples of Broadcasting: Broadcasting can be used in various scenarios, such as adding a scalar to an array, multiplying arrays of different shapes, or even combining arrays with different numbers of dimensions."""

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Create a 1D array to be broadcasted
arr2 = np.array([10, 20, 30])

# Add the 1D array to each row of the 3x3 array
result = arr1 + arr2

print(result)

[[11 22 33]
 [14 25 36]
 [17 28 39]]
